# Generated by Django 4.2.2 on 2024-01-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enkannur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=300)),
                ('lname', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('qualification', models.CharField(max_length=300)),
                ('phone', models.IntegerField(max_length=300)),
                ('course', models.CharField(max_length=300)),
                ('date', models.DateField(max_length=300)),
                ('staus', models.CharField(max_length=300)),
            ],
        ),
    ]
