# Generated by Django 4.2.2 on 2024-01-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_kannurpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knrregistraion',
            name='knr_amountpaid',
        ),
        migrations.RemoveField(
            model_name='knrregistraion',
            name='knr_dop',
        ),
        migrations.RemoveField(
            model_name='knrregistraion',
            name='knr_mod',
        ),
        migrations.AddField(
            model_name='kannurpayment',
            name='mod_payment',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
