# Generated by Django 4.2.2 on 2024-02-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_kzkdpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kzkdregistration',
            old_name='stu_id',
            new_name='kzstu_id',
        ),
    ]
